3 polymorphism
inix84/HW_Java_Core pull request #3
Opened 2024-12-09 18:34 UTC by inix84

2024-12-15 14:56 UTC, AleksandrZhukovJava requested changes

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/article/Article.java
> +    String textArticle; // тест статьи
private final

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Product.java
> +        return "возвращать имя товара"+name;
имело ввиду просто ,,name,, =)

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/article/Article.java
> +        return toString();
просто titleArticle + textArticle без лишних слов

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/Search/SearchEngine.java
> +        Searchable newSearchable = new Searchable() {
а зачем создавать еще 1 объект, в 14 строке у тебя уже создался SearchableName (название надо кстати с маленькой буквы), добавляй его
А newSearchable можно просто удалить

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/Search/SearchEngine.java
> +        this.Searchable = new Searchable[5];
размер надо принимать в конструктор, как-то так
public SearchEngine(int size) {
        this.Searchable = new Searchable[size];
}

2024-12-15 14:56 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/Search/SearchEngine.java
> +            System.out.println(Arrays.toString(Searchable));
печатать каждый раз не нужно

Тут нужно: 
1) Создать новый массив в начале списка на 5 элементов./
2) Заполнять его пока выполняется твой if (он написан верно)
3) Далее если 5 штук уже добавлено (нужно проверять каждый раз) то нужно приминить break
4) Осталось только вернуть из метода этот массив

В итоге архитектура будет примерно такая 
public Searchable[ ] search(String SearchableName) {
...создали новый массив на 5 элементов...
...прошлись циклом по нашему массиву Searchable (надо переименовать с маленькой буквы)
...пропускаем все данные через if который определит подходит ли нам элемент, если да, то запишем его в наш массив.
... проверим не заполнен ли наш массив для поиска, если да, то break

и все, на этом метод будет выполнен, можно добавить какие то выводы на экран

2024-12-15 16:18 UTC, inix84 commented on src/org/skypro/skyshop/product/Product.java
> +        return "возвращать имя товара"+name;
public String getName() {
        return name;

@Override
    public String gettingSearchTerm() {
        return name;
они одинаковые получаются? это ничего?

2024-12-15 16:47 UTC, inix84 commented on src/org/skypro/skyshop/Search/SearchEngine.java
> +            System.out.println(Arrays.toString(Searchable));
нулями все заполняется. посмотрите.
И я добавила в app только статьи, а как товары туда добавить?

2024-12-16 06:03 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/product/Product.java
> +        return "возвращать имя товара"+name;
Ничего, у этих методов разная семантика, хоть они и совпадают по телу

2024-12-17 09:32 UTC, AleksandrZhukovJava approved these changes

2024-12-17 09:32 UTC, AleksandrZhukovJava commented on src/org/skypro/skyshop/Search/SearchEngine.java
> +        Searchable[] searchable1 = new Searchable[5]; // создала новый массив, на 5 элементов
нужно ,,человекочитаемое,, название, что-то вроде result или resultProducts

2024-12-17 09:32 UTC, AleksandrZhukovJava commented on src/App.java
> +        SearchEngine.search("Хлеб");
Если ищешь статью и при это используешь внутри
return titleArticle + ":" + textArticle;
то и передавать внутрь надо сумму полей
SearchEngine.search(article1.gettingSearchTerm());

2025-01-27 15:57 UTC, merged